### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke interface method 'void android.view.Window$Callback.onDetachedFromWindow()' on a null object reference com.uxcam.internals.ag.onDetachedFromWindow

### ISSUE THREAD

**Issue by developerashish01** [uxcam/react-native-ux-cam#3]
I am getting this crash on react native app

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.Window$Callback.onDetachedFromWindow()' on a null object reference
       at com.uxcam.internals.ag.onDetachedFromWindow(:2)
       at com.android.internal.policy.DecorView.onDetachedFromWindow(DecorView.java:2274)
       at android.view.View.dispatchDetachedFromWindow(View.java:18537)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3818)
       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3903)
       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6947)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4278)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7099)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by susanuxcam** [comment]
hey @developerashish01, it seems to be similar to this one: https://github.com/negativetwelve/react-native-ux-cam/issues/74#issuecomment-603561404 - can you try this solution? If it doesn't work, can you tell me when this occurred? Any specific function calls?

**Comment by developerashish01** [comment]
No, Above solution is not answer. App is getting crash when React-Native-Video class appears

**Comment by susanuxcam** [comment]
Hey @developerashish01, thanks for letting me know. Can you send us a blank project with this crash?

**Comment by susanuxcam** [comment]
hey @developerashish01 , if you're still interested in using UXCam, can you try the most recent SDK? This crash shouldn't be occurring anymore

**Comment by developerashish01** [comment]
This issue is resolved.

**Comment by maykonmichel** [comment]
I'm having this problem even with the latest version 5.3.2

**Comment by PendragonDevelopment** [comment]
This problem persists in 5.3.3.

**Comment by m4r00p** [comment]
It is still crashing on  "react-native-ux-cam": "^5.3.4-beta.2",

Please help.

```
java.lang.NullPointerException
Attempt to invoke interface method 'void android.view.Window$Callback.onDetachedFromWindow()' on a null object reference

com.uxcam.internals.ag.onDetachedFromWindow(Unknown Source:2)
com.android.internal.policy.DecorView.onDetachedFromWindow(DecorView.java:1744)
android.view.View.dispatchDetachedFromWindow(View.java:19622)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3814)
android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4146)
android.view.ViewRootImpl.doDie(ViewRootImpl.java:7151)
android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4536)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:214)
android.app.ActivityThread.main(ActivityThread.java:7356)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by m4r00p** [comment]
I end up doing

```
  useEffect(() => {
    UXCam.occludeSensitiveScreen(true, false)
    return () => {
      UXCam.occludeSensitiveScreen(false, false)
    }
  }, [])
```

then it is not crashing anymore on that screen and hopefully, we don't need data from that screen. ;-D

**Comment by m4r00p** [comment]
Eh it is still crashing for some users on Android 10 with:

```
java.lang.NullPointerException
Attempt to invoke interface method 'void android.view.Window$Callback.onWindowFocusChanged(boolean)' on a null object reference

com.uxcam.internals.ag.onWindowFocusChanged(Unknown Source:2)
com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1728)
android.view.View.dispatchWindowFocusChanged(View.java:13789)
android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1496)
android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3120)
android.view.ViewRootImpl.access$1200(ViewRootImpl.java:156)
android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4854)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:225)
android.app.ActivityThread.main(ActivityThread.java:7563)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

Any clue @susanuxcam @uxcam-mobile?

**Comment by DFDIEGOH** [comment]
Hi @m4r00p ,

I understand that this issue happens when the method **occludeSensitiveScreen** is called right? Can you please downgrade to version 5.3.3 which is our latest stable version and see if this issue still persists?

Whats more, the method occludeSensitiveScreen should only receive one parameter (boolean) in order to work, are you using any type of wrapper for this?

In case you are trying to hide data from a specific screen, you can also try another workaround. You can call the method RNUxcam.pauseScreenRecording() right when the user enters this specific screen and call RNUxcam.resumeScreenRecording as soon as the user leaves this screen in order to avoid it from the recordings. 

Please let me know if you have further questions on this regard.

**Comment by DFDIEGOH** [comment]
Closed due to lack of responses.

**Comment by nimeshpoudel7** [comment]
java.lang.NullPointerException: 
  at com.uxcam.internals.ab.a (Unknown Source:50)
  at com.uxcam.internals.ab.b (Unknown Source:255)
  at com.uxcam.internals.ab.c (Unknown Source:14)

**Comment by nimeshpoudel7** [comment]
I am having this issue @DFDIEGOH
