### ISSUE TITLE
Possible memory leak in version 5.4.5

### ISSUE THREAD

**Issue by daniel-fs** [uxcam/react-native-ux-cam#84]
As of version 5.4.5 of react-native-ux-cam, the memory usage of my app keeps increasing nonstop, eventually leading to crashes.

When I launch my app, the memory usage starts at around 300 MBs. If I leave the app open without doing anything on it, 5-10 minutes later the memory usage has already doubled to 600 MBs and continues increasing. In Production, we are getting several OutOfMemoryError crashes daily due to this, specially in older devices and in longer sessions.

When testing the app in dev mode locally, if I disable the initialization of UXCam, the problem goes away and my app stays in the 300-350 MBs memory usage range. If I revert RN UXCam to version 5.4.4, the memory usage also gradually increases, but once it hits ~420 MBs, the garbage collector kicks in and the memory usage returns to the 300s range.

Crashes in Production due to low memory only started appearing after we updated the version of the RN UXCam package to the latest. Therefore, this problem seems to be only for the latest version of RN UXCam.

We are on **React-Native 0.71.4**.
Note that this was observed on **Android**. I am not sure if it is happening on iOS.

One of the crashes we saw in Production after updating RN UXCam to the latest version:

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM
       at com.uxcam.internals.gi$ac.a(SourceFile:25)
       at com.uxcam.internals.gi$ac.run(SourceFile:13)
```

We've also seen other UX Cam crashes we hadn't seen in the past. I'm not sure if they could be related:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Surface.unlockCanvasAndPost(android.graphics.Canvas)' on a null object reference
       at com.uxcam.internals.gi$ac.b(SourceFile:65)
       at com.uxcam.internals.gi$ac.a(SourceFile:32)
       at com.uxcam.internals.gi$ac.$r8$lambda$4a9ryxGPNmFklnTUlayJVarSDh8()
       at com.uxcam.internals.gi$ac$$ExternalSyntheticLambda0.onScreenshotTaken(:4)
       at com.uxcam.internals.ex.a(SourceFile:182)
       at com.uxcam.internals.ex.$r8$lambda$p9EQQfp1d8JGH4HD0ORIEqyDzuw()
       at com.uxcam.internals.ex$$ExternalSyntheticLambda2.onOcclusionComplete(:10)
       at com.uxcam.internals.ex.a(SourceFile:162)
       at com.uxcam.internals.ex.a(SourceFile:60)
       at com.uxcam.internals.ex.$r8$lambda$TSSEdNwGXk1CukAOSEY-t2-T53A()
       at com.uxcam.internals.ex$$ExternalSyntheticLambda0.onScreenshotTaken(:15)
       at com.uxcam.internals.fk.a(SourceFile:132)
       at com.uxcam.internals.fk.$r8$lambda$lZc-O-uFAubZ61MaIsQV_8H66As()
       at com.uxcam.internals.fk$$ExternalSyntheticLambda1.onScreenshotTaken(:4)
       at com.uxcam.screenshot.pixelcopyscreenshot.PixelCopyScreenshotImpl.a(SourceFile:37)
       at com.uxcam.screenshot.pixelcopyscreenshot.PixelCopyScreenshotImpl.$r8$lambda$kdG56TrE-yb-jcrK0IXE9AIOgGI()
       at com.uxcam.screenshot.pixelcopyscreenshot.PixelCopyScreenshotImpl$$ExternalSyntheticLambda0.onPixelCopyFinished(:6)
```

```
Fatal Exception: java.lang.IllegalStateException: Surface has already been released.
       at android.view.Surface.checkNotReleasedLocked(Surface.java:710)
       at android.view.Surface.unlockCanvasAndPost(Surface.java:431)
       at com.uxcam.internals.gi$ac.b(SourceFile:65)
       at com.uxcam.internals.gi$ac.a(SourceFile:32)
       at com.uxcam.internals.gi$ac.$r8$lambda$4a9ryxGPNmFklnTUlayJVarSDh8()
       at com.uxcam.internals.gi$ac$$ExternalSyntheticLambda0.onScreenshotTaken(:4)
       at com.uxcam.internals.ex.a(SourceFile:182)
       at com.uxcam.internals.ex.$r8$lambda$p9EQQfp1d8JGH4HD0ORIEqyDzuw()
       at com.uxcam.internals.ex$$ExternalSyntheticLambda2.onOcclusionComplete(:10)
       at com.uxcam.internals.ex.a(SourceFile:162)
       at com.uxcam.internals.ex.a(SourceFile:60)
       at com.uxcam.internals.ex.$r8$lambda$TSSEdNwGXk1CukAOSEY-t2-T53A()
       at com.uxcam.internals.ex$$ExternalSyntheticLambda0.onScreenshotTaken(:15)
       at com.uxcam.internals.fk.a(SourceFile:132)
       at com.uxcam.internals.fk.$r8$lambda$lZc-O-uFAubZ61MaIsQV_8H66As()
       at com.uxcam.internals.fk$$ExternalSyntheticLambda1.onScreenshotTaken(:4)
       at com.uxcam.screenshot.pixelcopyscreenshot.PixelCopyScreenshotImpl.a(SourceFile:37)
       at com.uxcam.screenshot.pixelcopyscreenshot.PixelCopyScreenshotImpl.$r8$lambda$kdG56TrE-yb-jcrK0IXE9AIOgGI()
       at com.uxcam.screenshot.pixelcopyscreenshot.PixelCopyScreenshotImpl$$ExternalSyntheticLambda0.onPixelCopyFinished(:6)
```

**Comment by gabrieluxcam** [comment]
@daniel-fs  hello, this has been fixed on our end and will come out in an upcoming release expected next week for the React Native package. 

Thanks for bringing this up

**Comment by ziga-hvalec** [comment]
any update for this?

**Comment by gabrieluxcam** [comment]
@ziga-hvalec Hello, this fix is coming within this week, please check https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES for further information once it releases.

**Comment by nahuelb** [comment]
Hello @gabrieluxcam 
We upgraded to version 5.4.8 this week because we were also having crashes on our app with this error, and according to Google Play Console we are still receiving crashes from this issue even after the upgrade.


<img width="525" alt="Screenshot 2023-07-07 at 12 52 07" src="https://github.com/uxcam/react-native-ux-cam/assets/6378996/effb041c-909a-4012-afe0-17d2a32e15a9">

**Comment by gabrieluxcam** [comment]
Hello @nahuelb  may I ask which React Native version you're using? And is it safe to assume these crashes that are still being reported come from app versions with the latest React Native UXCam version? Thanks!

@daniel-fs May I ask also if after upgrading SDK versions you have still experienced this crash on this updated app version? Thanks!

**Comment by nahuelb** [comment]
Hello @gabrieluxcam , FYI I submitted a ticket via Intercom, and I am currently following this issue with Diego from the uxcam support team.

We are using React Native v0.68.7.
Yes, we are filtering the errors by App Version to make sure they come from the release with the latest uxcam SDK version.

**Comment by jorgerojas26** [comment]
We are having this exact same issue.

"react-native-ux-cam": "5.4.5"
"react-native": "0.71.1"

**Comment by onmotion** [comment]
the same

<img width="1194" alt="Screenshot 2023-08-28 at 14 53 04" src="https://github.com/uxcam/react-native-ux-cam/assets/12899080/39410666-0502-4437-a8bd-efd0ea11d588">

**Comment by gabrieluxcam** [comment]
Hello @jorgerojas26 would you please test with the latest version of the SDK which is 5.4.10? Indeed in older versions we presented this kind of issue which should be since solved already in these newer versions. 

@onmotion Could you let me know which SDK version you're seeing this? If similar, please update to latest version. 

Additionally, in the upcoming version (ETA end of week on Sept 8th) we have introduced even further checks to avoid any possibilities of the SDK being the cause for this issue, so, if after upgrading to 5.4.10 the issue remains, please let me know and then test the latest once it releases. Thanks!

**Comment by jorgerojas26** [comment]
Hello @gabrieluxcam,

ok, i'll test it and come back in a few days with the results. Thanks.

**Comment by onmotion** [comment]
@gabrieluxcam we're using 5.4.10

**Comment by gabrieluxcam** [comment]
Thanks @onmotion in this case, as soon as the new version releases next week, you should please upgrade and monitor as we've added checks to avoid such scenarios from occurring due to UXCam. 

Please keep an eye [here](https://developer.uxcam.com/docs/changelog) for the release notes/updates 

Just in case, @jorgerojas26  please see this comment also.

**Comment by thisisadarshjais** [comment]
This has become a big blocker for us, Bcz the lower version of ux-cam can't be added to react native 0.71+ due to lower compileSdKversion and the higher version of ux-cam which has compatible compileSdkVersion is causing crash due to this issue.

**Comment by thisisadarshjais** [comment]
Seems like `5.4.4` is the only version that will work fine as of now for `react-native 0.70+`

**Comment by rohitmakwanauxcam** [comment]
@thisisadarshjais 
Could you please share details with UXCam regarding issue? 
we will have look into issue.

**Comment by thisisadarshjais** [comment]
The behaviour of issue that I am facing is same as what is described above by @daniel-fs

below is the attached screenshot for the logs I am getting while using the latest versions 

<img width="772" alt="image" src="https://github.com/uxcam/react-native-ux-cam/assets/117281532/584c7c55-58be-4543-904b-a5716405f931">

**Comment by daniel-fs** [comment]
As of version 5.4.11, the issue seems fixed on our end. Once the memory hits a certain threshold, it is cleared instead of growing indefinitely, just like in the last working version which was 5.4.4.

**Comment by gabrieluxcam** [comment]
This is great news @daniel-fs , I will then close this issue and please don't hesitate to reach out in any case. Thanks!
